### ISSUE TITLE
경제지표 크롤링 코드 제작

### ISSUE THREAD

**Issue by Becky-Kwon** [boostcampaitech6/level2-3-nlp-finalproject-nlp-10#52]
# 경제지표 = 수집 항목 정리
1. 코스피
2. 코스닥
3. 코스피200
4. 금 -> 금 선물 (국제 금값)
5. 비트코인
6. 다우존스 지수
7. 나스닥 종합지수
8. S&P500 지수
9. 환율(달러) - 달러(원화, 유로화)
10. WTI - 원유 oil 가격
9. 한국 채권 (5, 10 년 물)
10.  미국 채권 (5, 10 년 물)

**Comment by Becky-Kwon** [comment]
@jongwoncode  현재 만든건 날짜를 넣어주면 그 날짜거만 수집되는 건데,
여기서 날짜를 기간 처럼 넣어주면 전체 기간 수집하는 걸로 바꿀 수 있어요
그 코드 필요하시면 제가 일요일 오전에 해서 보내드릴게여

**Comment by jongwoncode** [comment]
@Becky-Kwon 일별로 수집하는거면 충분합니다. 고생하셨습니다~
